apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: django-application
  namespace: argocd

spec:
  project: default

  # Source of the Django application manifests
  source:
    repoURL: https://github.com/mohgeis/django-argocd-ci-demo.git 
    targetRevision: HEAD 
    path: k8s_manifests 
    
  # Destination cluster and namespace to deploy the application
  destination:
    server: https://kubernetes.default.svc
    namespace: django-app

  # Sync policy
  syncPolicy:
    automated: 
      prune: true 
      selfHeal: true
    syncOptions:
    - Validate=true
    - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 20s
        factor: 2
        maxDuration: 3m